function lua_main(con,str)
    -- testJava() 由 Java 注入。 Injected by Java.
    -- testJava("setting")
    -- tv:setText(testJava(con));
    -- tv:setTextSize(50);
    --android.home()
    droidlib.init()
    droidlib.test()
    droidlib.sleep(1000)
    lua_start_settings(con)
    droidlib.sleep(1000)
    droidlib.click(10, 700)
    droidlib.sleep(1000)
    droidlib.homePage()
    droidlib.sleep(1000)
    droidlib.touchDown(300, 0)
    droidlib.sleep(10)
    droidlib.touchScroll(300, 50)
    droidlib.sleep(10)
    droidlib.touchScroll(300, 100)
    droidlib.sleep(10)
    droidlib.touchScroll(300, 150)
    droidlib.sleep(10)
    droidlib.touchScroll(300, 200)
    droidlib.sleep(10)
    droidlib.touchScroll(300, 250)
    droidlib.sleep(10)
    droidlib.touchScroll(300, 300)
    droidlib.sleep(10)
    droidlib.touchScroll(300, 350)
    droidlib.sleep(10)
    droidlib.touchUp(300, 460)
    droidlib.close()
    --touchDown(30, 70)
    --lua_start_settings(con)
end

function lua_start_settings(con)
    local intent = luajava.newInstance("android.content.Intent")
    local c = luajava.newInstance("android.content.ComponentName", "com.android.settings", "com.android.settings.Settings")
    intent:setFlags(intent.FLAG_ACTIVITY_NEW_TASK)
    intent:setComponent(c)
    con:startActivity(intent)
end
